FlashCard.delete_all
FlashCard.create(word: "おはよう", meaning: "Good morning", pronunciation: "ohayou", language: "Japanese")
FlashCard.create(word: "こんにちは", meaning: "Good afternoon", pronunciation: "konnichiwa", language: "Japanese")
FlashCard.create(word: "こんばんは", meaning: "Good evening", pronunciation: "konbanwa", language: "Japanese")
FlashCard.create(word: "ありがとう", meaning: "Thank you", pronunciation: "arigatou", language: "Japanese")
FlashCard.create(word: "ごめんなさい", meaning: "Sorry", pronunciation: "gomennasai", language: "Japanese")
FlashCard.create(word: "はは", meaning: "Mother", pronunciation: "haha", language: "Japanese")
FlashCard.create(word: "ちち", meaning: "Father", pronunciation: "chichi", language: "Japanese")
FlashCard.create(word: "兄", meaning: "Brother", pronunciation: "ani", language: "Japanese")
FlashCard.create(word: "姉", meaning: "Sister", pronunciation: "ane", language: "Japanese")
FlashCard.create(word: "子供", meaning: "Children", pronunciation: "kodomo", language: "Japanese")
FlashCard.create(word: "pejorative", meaning: "expressing contempt or disapproval", pronunciation: "/pəˈjôrədiv/", language: "English")
FlashCard.create(word: "benign", meaning: "kind and gentle; not hurting anybody", pronunciation: "/bɪˈnaɪn/", language: "English")
FlashCard.create(word: "slavishly", meaning: "in a way that follows or copies somebody/something exactly without having any original thought at all", pronunciation: "/ˈsleɪvɪʃli/", language: "English")
FlashCard.create(word: "thoroughly", meaning: "very much; completely", pronunciation: "/ˈθʌrəli/", language: "English")
FlashCard.create(word: "vigilant", meaning: "very careful to notice any signs of danger or trouble", pronunciation: "/ˈvɪdʒɪlənt/", language: "English")
FlashCard.create(word: "yearn", meaning: "to want something very much, especially when it is very difficult to get", pronunciation: "/jɜːn/", language: "English")
FlashCard.create(word: "intruder", meaning: "a person who enters a building or an area illegally", pronunciation: "/ɪnˈtruːdə(r)/", language: "English")
FlashCard.create(word: "inevitably", meaning: "as is certain to happen", pronunciation: "/ɪnˈevɪtəbli/", language: "English")
FlashCard.create(word: "sophisticated", meaning: "having a lot of experience of the world and knowing about fashion, culture and other things that people think are socially important", pronunciation: "/səˈfɪstɪkeɪtɪd/", language: "English")
FlashCard.create(word: "painstakingly", meaning: "in a way that takes a lot of care, effort and attention to detail", pronunciation: "/ˈpeɪnzteɪkɪŋli/", language: "English")
